name = "Hugo Fresh"
license = "MIT"
licenselink = "https://github.com/anoduck/fresh-fork/blob/master/LICENSE.md"
description = "A fork of Stefan M. with darkness."
homepage = "https://github.com/anoduck/fresh-fork"
tags = ["responsive", "one page", "dark", "onepage", "company", "clean", "landing page"]
features = []
min_version = "0.45"

[author]
  name = "Stefan M."
  homepage = "https://github.com/StefMa"
